### PR TITLE
Adding Documentation #2

### PR DESCRIPTION
**Pull request by Priyanshu-official**
Added Readme.md file #2

### CODE REVIEW

**Comment by Priyanshu-official** [comment]
I have added that much info I can collect.
@rexdivakar  please Review and let me know if any changes needed.

**Comment by rexdivakar** [comment]
Good job 👌 @Priyanshu-official

**Comment by Priyanshu-official** [comment]
@rexdivakar Hello 
sorry to interrupt you
But as you know  Hactobesfest rule is change 
**in Repo:  Hactobesfest label and 
in PR: Hactobesfest-accepted label should be there then It will count**

In my PR  Hactobesfest-accepted are show if can Please can label

**Comment by rexdivakar** [comment]
Yup, We will make the changes soon Thanks @Priyanshu-official

**Pull request merged**
